language: node_js
node_js:
  - "10" # This is the node js version

before_script:
  - npm i gitfolio -g

script:
  - gitfolio build kylelobo --theme dark --fork --sort star --order desc
  - cp -a dist/. ../kylelobo.github.io
  - rm -rf dist/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  keep_history: true
#   local_dir: dist
  on:
    branch: master
target_branch: master
